name: CI/CD

on:
  push:
    branches: [ "main" ]
 

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: | 
        cd frontend
        npm install
        cd ../backend
        npm install

    - name: Build React App
      run: |
        cd frontend
        npm run build

    - name: Run Tests
      run: |
        cd backend
        npm test

  cd:

    runs-on: ubuntu-latest
    needs: ci
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
 
    - name: Build the Docker image
      run: |
        docker build . --file ./frontend/Dockerfile --tag karan999/frontend:latest
        docker build . --file ./backend/Dockerfile --tag karan999/backend:latest
    - name: Push the Docker image
      run: |
        docker push karan999/frontend:latest
        docker push karan999/backend:latest
  
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GKE_SA }}

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
        location: ${{ secrets.GKE_CLUSTER_ZONE }}
